# Generated by Django 4.2.1 on 2023-06-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография продукта', 'verbose_name_plural': 'Фотографии продуктов'},
        ),
    ]
