# Generated by Django 4.2.1 on 2023-08-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productfavorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/no_image.png', null=True, upload_to='product_images/', verbose_name='Фотография'),
        ),
    ]
