# Generated by Django 4.2.1 on 2023-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/no_image.png', max_length=1000, null=True, upload_to='product_images/', verbose_name='Фотография'),
        ),
    ]
