version: "3"
services:
  db:
    image: postgres:13
    container_name: shopify_db
    environment:
      - POSTGRES_DB=shopify
      - POSTGRES_USER=kuma
      - POSTGRES_PASSWORD=geeksstudents
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py createsuperuser --noinput && python3 manage.py settings && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://kuma:geeksstudents@db:5432/shopify
      DJANGO_SUPERUSER_USERNAME: admin  # Укажите желаемое имя пользователя здесь
      DJANGO_SUPERUSER_EMAIL: admin@example.com  # Укажите желаемый адрес электронной почты здесь
      DJANGO_SUPERUSER_PASSWORD: admin1234  # Укажите желаемый пароль здесь

volumes:
  postgres_data: