version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=shopify
      - DB_USER=kuma
      - DB_USER_PASSWORD=geeksstudents
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=shopify
      - POSTGRES_USER=kuma
      - POSTGRES_PASSWORD=geeksstudents
    ports:
      - "5432:5432"