version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=shopify
      - DB_USER=kuma
      - DB_USER_PASSWORD=geeksstudents
      - DB_HOST=db
      - DB_PORT=5432
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: shopify_db
    environment:
      - POSTGRES_DB=shopify
      - POSTGRES_USER=kuma
      - POSTGRES_PASSWORD=geeksstudents
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"