version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn shopify.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kuma
      - POSTGRES_PASSWORD=geeksstudents
      - POSTGRES_DB=shopify

volumes:
  postgres_data: