# Generated by Django 4.2.1 on 2023-08-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Код оплаты биллинга'),
            preserve_default=False,
        ),
    ]
