# Generated by Django 4.2.1 on 2023-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_slug_alter_shop_banner_alter_shop_description_and_more'),
        ('billing', '0003_alter_billing_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='shops',
            field=models.ManyToManyField(related_name='billing_shops', to='shops.shop', verbose_name='Магазины'),
        ),
    ]
