# Generated by Django 4.2.1 on 2023-07-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='shop_banners/', verbose_name='Баннер магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='domain',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на магазин'),
        ),
    ]
