# Generated by Django 4.2.1 on 2023-07-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_slug_alter_shop_banner_alter_shop_description_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_manages', to='shops.shop', verbose_name='Магазин'),
        ),
    ]
