# Generated by Django 4.2.1 on 2023-08-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chat ID'),
        ),
    ]
