# Generated by Django 4.2.1 on 2023-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Client', 'Client'), ('Partner', 'Partner')], default='Client', max_length=100, verbose_name='Роль пользователя'),
        ),
    ]
