# Generated by Django 4.2.1 on 2023-08-06 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_slug_alter_shop_banner_alter_shop_description_and_more'),
        ('users', '0004_alter_user_address_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес проживания', max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефонный номер менеджера для контакта', max_length=50, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Промо код пользователя', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Магазин на котором менеджер может создавать товары и управлять ими', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_manages', to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, help_text='Chat ID менеджера для получения уведомления с маркетплейса', null=True, verbose_name='Chat ID'),
        ),
    ]
