# Generated by Django 4.2.1 on 2023-06-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_partnership_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Client', 'Client'), ('Partner', 'Partner'), ('Manager', 'Manager')], default='Client', max_length=100, verbose_name='Роль пользователя'),
        ),
    ]
