# Generated by Django 4.2.1 on 2023-06-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
